### ISSUE TITLE
Particle should be a subclass for scene.Rect

### ISSUE THREAD

**Issue by cclauss** [Pythonistapro777/Magic8Ball#8]

**Comment by cclauss** [comment]
OK.  Now get rid of particle.cells.  Use particle everywhere where you used particles.cells before because each Particle is now a Rect.

Get rid of attackx and use particle.x everywhere where you used attackx before.

Get rid of attacky and use particle.y everywhere where you used attacky before.

**Comment by dayoogu** [comment]
Ok

**Comment by dayoogu** [comment]
cclauss

**Comment by dayoogu** [comment]
It doesn't work when I do that
